### ISSUE TITLE
Using custom domain for module path is suspicious

### ISSUE THREAD

**Issue by elliot-u410** [mtoohey31/iter#18]
I'd love to use this, but as-is I have to vendor it or something otherwise I run the risk of a single developer letting his domain lapse and ruining my application dependencies. Consider changing this.

**Comment by mtoohey31** [comment]
Hi @elliot-u410, I can understand why you'd be concerned about this kind of thing. I chose to use my own domain since I'm not sure that I'll want to host my code on GitHub for forever, so I want to have the option of switching Git hosting providers without everyone who depends on my libraries having to update their URLs. I think "suspicious" is a bit of an unfair description, but I do get why it's easier to trust a GitHub domain than mine.

I think there's a way I can allow those that would prefer to use a GitHub module path to do so, while keeping my own domain on the main branch. I've created [a branch](https://github.com/mtoohey31/iter/tree/github-mod-path) where I've changed the module path to `github.com/mtoohey31/iter/v2`. According to my testing, if you add `"github.com/mtoohey31/iter/v2"` to your project's imports, then run `go get github.com/mtoohey31/iter/v2@github-mod-path`, it will pull things directly from GitHub, with no reference to my domain. I'll have to remember to keep that branch up-to-date (feel free to bug me if I forget, though I'll try). I'm also not completely sure how this will play with `go get -u`, but the worst-case scenario is that Go pulls the latest version of the main branch directly from GitHub, then complains about the mod path mismatch, in which case you'll have to run `go get github.com/mtoohey31/iter/v2@github-mod-path` again.

Does that sound like a fair compromise?

**Comment by elliot-u410** [comment]
@mtoohey31 Thank you very much. I actually found a better way!

I added this to `go.mod`:
```
replace mtoohey.com/iter/v2 v2.0.0 => github.com/mtoohey31/iter/v2 v2.0.0
```

This is *probably* nothing more than what your server is doing anyway. However, the "suspicious" aspect in my case has to do with the fact that I'm very concerned about supply chain attacks and my software often deals with critical secrets. It's much easier for `mtoohey.com` to be attacked than it is for `github.com`.

**Comment by mtoohey31** [comment]
Ah, that's a much nicer solution!

> This is _probably_ nothing more than what your server is doing anyway.

That is the case, the source is [here](https://github.com/mtoohey31/mtoohey.com/blob/main/src/lib/GoMeta.svelte), but of course, there's no way for you to be certain that the code there is what's running on the server.

> It's much easier for `mtoohey.com` to be attacked than it is for `github.com`.

That's fair. Thanks for looking into things yourself and finding that solution. I'm going to delete the alternate branch so I don't have to worry about keeping it updated, and I'll point people to this thread if the same issue ever comes up again. Best of luck with your project!
