### ISSUE TITLE
`iter.Receive`/`iter.Send` not use `*chan T` as parameter

### ISSUE THREAD

**Issue by cjwcommuny** [mtoohey31/iter#24]
Currently, `iter.Receive` and `iter.Send` use `*chan T` as the type of the parameter:

https://github.com/mtoohey31/iter/blob/177a55357b43e42911662ab41ae1e5ac5cddee02/chan.go#L8C1-L8C1

https://github.com/mtoohey31/iter/blob/177a55357b43e42911662ab41ae1e5ac5cddee02/chan.go#L20

However [it's not considered a good practice](https://stackoverflow.com/questions/44351159/using-pointer-to-channel)

Also, `iter.Receive` should use `<-chan T` and `iter.Send` should use `->chan T`

**Comment by mtoohey31** [comment]
Thanks, both good suggestions! I clearly didn't understand channels very well when I wrote this code originally. Changing the types would be a breaking change though, and I'm reluctant to release a new major version just for this, since nothing is actually broken. For now I have the changes on the [v3 branch](https://github.com/mtoohey31/iter/tree/v3a). I'll release them with that new major version if/when it becomes necessary. In the meantime, if you'd like to use those changes, you should be able to use the code in that branch by running something like `go get -u mtoohey.com/iter/v3@ef87de520c984b8f8dee3244d6e4b0dd62c11e7e`.
